[sbatch-args]
time = "04:00:00"
mem = 16000
nodes = 1
cpus-per-task = 2
job-name = "xnat2bids"
output = "./logs/%J.txt"
mail-user = "ford_mcdonald@brown.edu"
mail-type = "ALL"

[xnat2bids-args]
session = "XNAT_E00114"
bids_root = "/gpfs/data/bnc/shared/bids-export/"
data_dir = "/gpfs/data/bnc"
version = ""
bids_root_dir=""
host="https://xnat.bnc.brown.edu"
session-suffix=-1
bidsmap_file=""
includeseq=[]
skipseq=[]
verbose=0
overwrite=false