[sbatch-args]
time = "04:00:00"
mem = 16000
nodes = 1
cpus = 2
job = "xnat2bids"
output = "../logs/%J.txt"
email = "ford_mcdonald@brown.edu"

[xnat2bids-args]
data_dir = "/gpfs/data/bnc"
bids_root = ""
version = ""
session = "XNAT_E00114"
bids_root_dir=""
host="https://xnat.bnc.brown.edu"
session_suffix=-1
bidsmap_file=""
includeseq=[]
skipseq=[]
log_id=""
verbose=""
overwrite="False"
cleanup=""