[slurm-args]
time = "01:00:00"
mem = 8000
nodes = 2
job-name = "xnat2bids"
output = "/gpfs/data/bnc/scratch/logs/%J.txt"
mail-user = "example-user@brown.edu"
mail-type = "ALL"

[xnat2bids-args]
session = "XNAT_E00080"
version = ""
bids_root_dir=""
bids_root = "/gpfs/data/bnc/shared/bids-export/"
host="https://xnat.bnc.brown.edu"
bidsmap-file=""
includeseq=[1]
overwrite=true
